### PR TITLE
add benchmarks project

### PR DESCRIPTION
**Pull request by mehalick**

### CODE REVIEW

**Comment by mehalick** [comment]
@Tarek-Samy Can you take a look and let me know what you think? I'm running benchmarks on CLR, Core, and Mono, results in the artifacts folder.

**Comment by ghost** [comment]
Okay, i'll take a look.

**Comment by mehalick** [comment]
Here are the results: https://github.com/mehalick/Xaki/blob/7f6c6dac08c701a9398097a2f5e4f0ce4aec5726/benchmarks/Xaki.Benchmarks/BenchmarkDotNet.Artifacts/results/Xaki.Benchmarks.Benchmarks-report-github.md

Surprising much slower on Mono but it could be related to my machine; or perhaps there's room to optimize. Could also be JSON.Net performance on Mono and I'm not sure if it's a big deal.

**Comment by ghost** [comment]
Deep is not actually deep though, right? You are not benchmarking the new code I sent you yesterday?

Have you run the benchmarks as described here: https://benchmarkdotnet.org/articles/guides/how-to-run.html

Also maybe add a GC diagnoser : https://benchmarkdotnet.org/articles/configs/diagnosers.html

**Comment by mehalick** [comment]
Right, I'm running against `master` which I know is still waiting on the deep implementation.

Regarding running, just doing:

```
dotnet run -c Release --framework netcoreapp2.1
```

For the GC diagnoser, I'll check it out, definitely haven't seen that before.

**Pull request merged**
